### PR TITLE
Swift 3 support

### PR DESCRIPTION
**Pull request by Eke**
Added Swift 3 support and switched to `Cocoapods` instead of `Carthage`
### Updated Libs
- `Quick`
- `Nimble`
- `SCrypto`

### CODE REVIEW

**Comment by hannesstruss** [comment]
@nickvelloff @eke Let's merge this?

**Comment by nickvelloff** [comment]
@hannesstruss @Eke yes LGTM 🚢

**Comment by jonnor** [comment]
@Eke  @nickvelloff going to merge this? Propose also doing a version bump `0.3.x` and a release

**Comment by Eke** [comment]
@jonnor @hannesstruss will do today

**Pull request merged**
